name: my first workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: list
              run: ls -ltra
            - name: execute shell
              run: | 
                    
                    chmod +x .github/workflows/asciishell.sh 
                    .github/workflows/asciishell.sh 
    job-2test:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: grep -i "dragon" gragon.txt
    job-3deploy:
        needs: job-2test
        runs-on: ubuntu-latest
        steps:
            - name: CD
              run: |
                cat gragon.txt
                echo "deploying"

            

          
